site_name: Xiaoyu's Blog
# repo_url: https://github.com/chuxiaoyu/blog
copyright: '&copy; 2022-2023 by Xiaoyu Chu'

theme:
  name: material
  favicon: image/logo.png
  logo: image/avatar.jpg
  font:
    text: Crimson Pro
  palette:
    primary: indigo
    # accent: black
  # feature:
  #   tabs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.expand

repo_name:
  chuxiaoyu/blog


nav:
# - About: https://chuxiaoyu.cn/
- ğŸ  Home: index.md
- ğŸ¤– Machine Learning:
  - ç›®å½•: ml-index.md
  - CS224nè‡ªç„¶è¯­è¨€å¤„ç†:
    - Lecture07 æœºå™¨ç¿»è¯‘ã€seq2seqæ¨¡å‹ã€æ³¨æ„åŠ›æœºåˆ¶: machine-learning/Lecture07.md
    - Lecture09 è‡ªæ³¨æ„åŠ›æ¨¡å‹ã€Transformers: machine-learning/Lecture09.md
    - Lecture10 é¢„è®­ç»ƒ: machine-learning/Lecture10.md
    - Lecture11 é—®ç­”ç³»ç»Ÿ: machine-learning/Lecture11.md
  - åŸºäºtransformersçš„NLP:
    - Task01 NLPå­¦ä¹ æ¦‚è§ˆ: machine-learning/nlp-transformer-task01.md
    - Task02 å­¦ä¹ Attentioinå’ŒTransformer: machine-learning/nlp-transformer-task02.md
    - Task03 å­¦ä¹ BERT: machine-learning/nlp-transformer-task03.md
    - Task04 å­¦ä¹ GPT: machine-learning/nlp-transformer-task04.md
    - Task05 ç¼–å†™BERTæ¨¡å‹: machine-learning/nlp-transformer-task05.md
    - Task06 BERTåº”ç”¨ã€è®­ç»ƒå’Œä¼˜åŒ–: machine-learning/nlp-transformer-task06.md
    - Task07 ä½¿ç”¨Transformersè§£å†³æ–‡æœ¬åˆ†ç±»ä»»åŠ¡: machine-learning/nlp-transformer-task07.md
  - æ·±å…¥æµ…å‡ºPyTorch:
    - Chapter01-02 PyTorchçš„ç®€ä»‹å’Œå®‰è£…ã€PyTorchåŸºç¡€çŸ¥è¯†: machine-learning/pytorch-chap01-02.md
    - Chapter03 PyTorchçš„ä¸»è¦ç»„æˆæ¨¡å—: machine-learning/pytorch-chap03.md
    - Chapter04 PyTorchåŸºç¡€å®æˆ˜â€”â€”FashionMNISTå›¾åƒåˆ†ç±»: machine-learning/pytorch-chap04.md
- ğŸ’¾ Computer System:
  - ç›®å½•: sys-index.md
  - Nand2Tetris è®¡ç®—æœºç³»ç»Ÿè¦ç´ :
    - Nand2Tetris Part1 (Hardware): system/nand2tetris_part_1.md
    - Nand2Tetris Part2 (Software): system/nand2tetris_part_2.md
  - ML Compilation æœºå™¨å­¦ä¹ ç¼–è¯‘:
    - 01 æœºå™¨å­¦ä¹ ç¼–è¯‘æ¦‚è¿°: system/ml-compilation-01.md
    - 02 å¼ é‡ç¨‹åºæŠ½è±¡: system/ml-compilation-02.md
    - 03 å¼ é‡ç¨‹åºæŠ½è±¡æ¡ˆä¾‹ç ”ç©¶ï¼šTensorIR: system/ml-compilation-03.md
    - 04 ç«¯åˆ°ç«¯æ¨¡å‹æ•´åˆ: system/ml-compilation-04.md
    - 05 è‡ªåŠ¨ç¨‹åºä¼˜åŒ–: system/ml-compilation-05.md
- ğŸ“Š Data Science:
  - Sequences, time series, and prediction: data-science/sequences-time-series-and-prediction.md
- ğŸ“ Posts:
  - Types of CS Paper: posts/post-types-of-paper.md
  - Open Source Projects: posts/open-source-projects.md
- ğŸ‘©â€ğŸ’» About: https://www.chuxiaoyu.cn/







plugins:
  - search
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
    - 'js/extra.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'